language: ruby
rvm:
  - 1.9.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp ./config/travis_database.yml ./config/database.yml"
  - "bundle exec rake db:setup"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake sunspot:solr:start"

script: "bundle exec rake cucumber"
