language: ruby
rvm:
  - 2.0.0
before_script:
  - "export DISPLAY=:99.0"
  - "export SESSION_SECRET='BC56FB924908AF3DC14A32B3FFE8E0D8B6A46D19'"
  - "sh -e /etc/init.d/xvfb start"
  - "cp ./config/travis_database.yml ./config/database.yml"
  - "mkdir -p tmp/cache"
  - "bundle exec rake db:setup"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake sunspot:solr:start"

script: "bundle exec rake cucumber && bundle exec rake spec"

after_script:
  - "curl https://raw.githubusercontent.com/crowdint/rubycritic-publisher/master/push-rubycritic-report.sh?token=AAIQ576md-DiYe-c996WQeGaSOLdzNxYks5Uvo9DwA%3D%3D | bash -s $PUBLISHER_PROJECT $PUBLISHER_USER $PUBLISHER_PASSWORD $PUBLISHER_HOST"
